name: Create Github Release
on: push
permissions:
  contents: write
jobs:
  build:
    name: Create Github Release
    runs-on: ubuntu-latest
    outputs:
      myOutput: ${{ steps.step1.outputs.myOutput }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Read file and store value in variable
        run: |
          MY_VERSION=$(grep '^versionName' gradle.properties | cut -d'=' -f2)
          echo "Version name from gradle.properties: $MY_VERSION"
          echo "##[set-output name=versionName]$MY_VERSION"
        shell: bash
      - name: Step 1
        id: step1
        run: echo "::set-output name=myOutput::1.0.4"
  #      - uses: ncipollo/release-action@v1
  #        with:
  #          tag: ${{ steps.build.outputs.versionName }}
  #          replacesArtifacts: true
  #          artifacts: build/libs/detekt-rules.jar

  job2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup variables in local.properties
        run: |
          echo "signing_keyId=${{secrets.SIGNING_KEY_ID}}" > local.properties
          echo "signing_password=${{secrets.SIGNING_PASSWORD}}" >> local.properties
          echo "username=${{secrets.MAVEN_CENTRAL_USER_NAME}}" >> local.properties
          echo "password=${{secrets.MAVEN_CENTRAL_PASSWORD}}" >> local.properties
      - name: Setup gpg private key
        run: |
          echo "${{secrets.GPG_PRIVATE_KEY}}" > maven-secret-key.asc
      - name: Step 2
        run: echo "Output from Job 1 ${{ needs.build.outputs.myOutput }}"
      - name: Generate jar
        run: |
          ./gradlew jar
          echo $versionName
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.myOutput }}
          replacesArtifacts: true
          artifacts: build/libs/detekt-rules.jar