name: Code checks on Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
      - 'release/**'
      - 'dev'
jobs:
  pull_request_checks:
    name: Code checks on Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Setup variables in local.properties
        run: |
          echo "signing_keyId=${{secrets.SIGNING_KEY_ID}}" > local.properties
          echo "signing_password=${{secrets.SIGNING_PASSWORD}}" >> local.properties
          echo "username=${{secrets.MAVEN_CENTRAL_USER_NAME}}" >> local.properties
          echo "password=${{secrets.MAVEN_CENTRAL_PASSWORD}}" >> local.properties
      - name: Setup gpg private key
        run: |
          echo "${{secrets.GPG_PRIVATE_KEY}}" > maven-secret-key.asc
      - name: Run unit tests
        run: ./gradlew test